#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#


obj-$(CONFIG_MTK_CAMERA_ISP_RAW_SUPPORT) += src/
#obj-y += owe/
obj-$(CONFIG_MTK_CAMERA_ISP_WPE_SUPPORT) += wpe/
#obj-y += dpe/
#obj-y += tsf/
obj-$(CONFIG_MTK_CAMERA_ISP_SUPPORT) += mfb/
obj-$(CONFIG_MTK_CAMERA_ISP_SUPPORT) += fdvt/
obj-$(CONFIG_MTK_CAMERA_ISP_PDA_SUPPORT) += pda/
