ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(srctree)/drivers/hid/stylus/
obj-$(CONFIG_I2C_HID_ILITEK)				+= i2c-hid-ilitek.o
i2c-hid-ilitek-y := hid-ilitek_9882t.o \
		ilitek_9882t.o \
		ilitek_9882t_i2c.o \
		ilitek_9882t_core.o \
		ilitek_9882t_ic.o \
		ilitek_9882t_touch.o \
		ilitek_9882t_flash.o \
		ilitek_9882t_mp.o \
		ilitek_9882t_node.o
