ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
obj-$(CONFIG_HID_TOUCH_METRICS) += hid_touch_metrics.o
hid_touch_metrics-y := hid_touch_metrics_core.o \
		touch_module_id.o
